version: '3.3'
services:
  ansible_client:
    build:
      context: .
      dockerfile: ansible_client.dockerfile
    image: ansible_workshop/osx_client
    container_name: ansible_client
    networks:
      my_network:
        ipv4_address: 172.16.238.10
    command: tail -f /dev/null
    volumes:
      - "../hosts/hosts_inventory.ini:/etc/ansible/hosts"
      - "../playbooks:/root/playbooks/"
      - "../examples:/root/examples/"
      - "./client_known_hosts:/root/.ssh/known_hosts"
    working_dir: /root

  some_server:
    build:
      context: .
      dockerfile: ./server.dockerfile
    image: ansible_workshop/osx_server
    container_name: some_server
    networks:
      my_network:
        ipv4_address: 172.16.238.11
    volumes:
      - "./server_keys:/etc/ssh"
    command:  bash -c "/usr/sbin/sshd && tail -f /dev/null"
    working_dir: /root


networks:
    my_network:
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
