version: '3.3'
services:
  ansible_client:
    build:
      context: .
      dockerfile: ansible_client.dockerfile
    image: ansible_workshop/osx_client
    container_name: ansible_client
    networks:
      my_network:
        ipv4_address: 172.16.238.10
    command: tail -f /dev/null

  some_server:
    build:
      context: .
      dockerfile: ./server.dockerfile
    image: ansible_workshop/osx_server
    container_name: some_server
    networks:
      my_network:
        ipv4_address: 172.16.238.11
    command:  bash -c "/usr/sbin/sshd && tail -f /dev/null"

networks:
    my_network:
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
