all:
  children:
    workshop:
      children:
        my_nodes:
          children:
            local:
              hosts:
                localhost
              vars:
                ansible_host: 127.0.0.1
                ansible_connection: local
            remotes:
              hosts:
                some_server
        not_my_nodes:
#  vars:
#    ansible_python_interpreter: auto_silent
